name: 自动运行

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 每天运行 6:00, 17:00 两次 (UTC+8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 保持仓库运行
        uses: EndBug/add-and-commit@v9.1.0
        with:
          commit: --allow-empty
          message: 'A empty commit on a trash branch to keep alive the repo'
          new_branch: keep-alive
